engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 40  // default threshold
  eslint:
    enabled: true
    channel: "eslint-3"  // supports airbnb-base config
    checks:
      complexity:
        enabled: true
  csslint:
    enabled: true
