extends:
  - airbnb-base
  - plugin:meteor/recommended

plugins:
  - import
  - meteor

settings:
  import/core-modules:  # don't lint for these missing packages in package.json
    - electron  # 'electron-prebuilt' is being used

rules:
  indent:
    - 2  # error
    - 4  # number of spaces
