extends: airbnb-base

plugins:
  - import

settings:
  import/core-modules:  # don't lint for these missing packages in package.json
    - electron  # 'electron-prebuilt' is being used

rules:
  indent:
    - 2  # error
    - 4  # number of spaces

globals:
  i18n: true  # don't warn about missing 'i18n' declaration
