extends: airbnb-base

plugins:
  - import

settings:
  import/core-modules:  ## don't lint for these missing packages in package.json
    - electron  ## 'electron' is only needed as devDependency / global installation

rules:
  indent:
    - error
    - 4  ## number of spaces
  no-console: off  ## allowed for chrome dev-console
  padded-blocks: off
  arrow-body-style: off
  prefer-arrow-callback: off
  no-underscore-dangle: off
  comma-dangle:
    - error
    - only-multiline

globals:  # don't warn about missing declarations
  i18n: true
  mist: true
  beforeEach: true
  LocalStore: true
  web3: true
  Tabs: true
  Tracker: true
  _: true
