extends: airbnb-base

plugins:
  - import

settings:
  import/core-modules:  # don't lint for these missing packages in package.json
    - electron  # 'electron' is only needed as devDependency / global installation

rules:
  indent:
    - 2  # error
    - 4  # number of spaces

globals:  # don't warn about missing declaration
  i18n: true
