sudo: required
dist: trusty

os: osx
osx_image: xcode8.0

language: node_js
node_js:
- '4.3.0'

cache:
  timeout: 1000
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.meteor
  - interface/.meteor/local
  - $HOME/.cache

#language: node_js
#node_js:
#- "4"

#branches:
#  only:
#    - develop

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "brew update" ; fi  # windows dependencies
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "brew install gnu-tar graphicsmagick xz libicns" ; fi  # linux dependencies

install:
- npm install -g meteor-build-client
- npm install -g gulp
- npm install

before_script:
- "curl https://install.meteor.com/ | sh"
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "gulp update-nodes --platform linux" ; fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "gulp update-nodes --platform all" ; fi
- gulp update-nodes --platform linux

script:
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "gulp --platform=linux" ; fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "gulp --platform=all" ; fi
- travis_wait 100 gulp wallet --platform=linux


#notifications:
#  email:
#    - mist@ethereum.org
