osx_image: xcode7.3

sudo: required
dist: trusty

matrix:
  include:
    - os: osx
    - os: linux

#cache:
#  directories:
#  - node_modules
#  - $HOME/.electron
#  - $HOME/.cache

language: node_js
node_js:
- "4"

branches:
  only:
    - develop

before_install:
# win dependencies
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; "brew update" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; "brew install wine --without-x11 mono" ; fi
# linux dependencies
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; "brew install gnu-tar graphicsmagick xz" ; fi

install:
#- nvm install 6
- npm install -g meteor-build-client
- npm install -g gulp
- npm install
- npm prune

before_script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; "export DISPLAY=:99.0" ; fi 
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; "sh -e /etc/init.d/xvfb start" ; fi
#  - "sleep 3" # give xvfb some time to start
- "curl https://install.meteor.com/ | sh"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; "gulp update-nodes --platform linux" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; "gulp update-nodes --platform all" ; fi

script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; "gulp --platform=linux" ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; "gulp --platform=all" ; fi

#notifications:
#  email:
#    - mist@ethereum.org
