os: osx
osx_image: xcode7.3
brew_packages:
- gnu-tar
- graphicsmagick
- xz

language: node_js
node_js:
- '4.3.0'

cache:
  timeout: 1000
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.meteor
  - interface/.meteor/local
  - $HOME/.cache

#language: node_js
#node_js:
#- "4"

#branches:
#  only:
#    - develop

before_install:
- brew update
- brew install wine --without-x11 mono gnu-tar graphicsmagick xz

install:
- npm install -g meteor-build-client
- npm install -g gulp
- npm install

before_script:
- "curl https://install.meteor.com/ | sh"
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "gulp update-nodes --platform linux" ; fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "gulp update-nodes --platform all" ; fi
- gulp update-nodes --platform all

script:
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then "gulp --platform=linux" ; fi
#- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then "gulp --platform=all" ; fi
- travis_wait 100 gulp wallet --platform=mac


#notifications:
#  email:
#    - mist@ethereum.org
